# Generated by Django 3.1 on 2020-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201011_1129'),
        ('polls', '0002_auto_20201017_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voter', to='profiles.Profile'),
        ),
    ]
