# Generated by Django 3.1 on 2020-10-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201017_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
