# Generated by Django 3.1 on 2020-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200901_1626'),
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='profiles.Profile'),
        ),
    ]
