# Generated by Django 3.1 on 2020-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_auto_20200901_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
